info:
  contact: {}
paths:
  /api/v1/companies/create:
    post:
      consumes:
      - application/json
      description: Create the company's information
      produces:
      - application/json
      responses: {}
      security:
      - CookieAuth: []
      summary: Create Company Information
      tags:
      - Company
  /api/v1/companies/get/all:
    get:
      consumes:
      - application/json
      description: Retrieves the Company's information
      produces:
      - application/json
      responses: {}
      security:
      - CookieAuth: []
      summary: Get Company Information
      tags:
      - Company
swagger: "2.0"
