info:
  contact: {}
paths:
  /api/v1/companies/create:
    post:
      consumes:
      - application/json
      description: Create the company's information
      produces:
      - application/json
      responses: {}
      security:
      - CookieAuth: []
      summary: Create Company Information
      tags:
      - Company
swagger: "2.0"
